name: Submit Sitemap to Search Engines
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *' # Daily at 12PM UTC

jobs:
  submit-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Submit to Google
        run: |
          curl -s "https://www.google.com/ping?sitemap=https://add-your-site.pages.dev/sitemap.xml"
      
      - name: Submit to Bing
        run: |
          curl -s "https://www.bing.com/ping?sitemap=https://add-your-site.pages.dev/sitemap.xml"
      
      - name: Submit to Yandex
        run: |
          curl -s "https://webmaster.yandex.com/ping?sitemap=https://add-your-site.pages.dev/sitemap.xml"
